### ISSUE TITLE
Default bookmarks

### ISSUE THREAD

**Issue by ghost** [JTechMe/JumpGo#14]
After installing JumpGo, a bookmark for "Jehovah's Witnesses" appears in the bookmark list. Assuming that this was added by mistake or that it is a bug, I would like to ask the developers to clarify/fix this.

**Comment by licaon-kter** [comment]
By design: https://github.com/JTechMe/JumpGo/blob/51b4a5f07ae0168aa4d71c572e4ebcc05c68a27a/app/src/main/res/raw/default_bookmarks.dat#L6

**Comment by nutellarlz** [comment]
Licaon-kter is correct, JumpGo was originally designed for use by myself and several if my friends who access jw.org on a daily basis so the bookmark was added for our(my friends and I) convenience. Although this seems to be to the public's annoyance.
