### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by axeforeverjumo** [JTechMe/JumpGo#33]
if i dont want to have the defaults bookmarks, how can i do? I want to place google, yahoo, etc bookmarks
Your app is amazing!, i donwloaded, and i am sharing it, but i download the apk and i cant get it why i have all this bookmarks...

**Comment by IriaSomobu** [comment]
You can just remove it, cant you?

**Comment by nutellarlz** [comment]
Sorry for the late(really late) reply, was away.
The default bookmarks are provided for quick access to common links and some JumpGo/JTM related links. You can easily delete the bookmarks but they are provided by default for the majority...
