### ISSUE TITLE
MPEG-4 ASP support / adaptive bitrate

### ISSUE THREAD

**Issue by herndlm** [JTechMe/JumpGo#7]
Hi, I'm having problems with videos on CM13 an created an issue "upstream", but nobody responded:
https://github.com/anthonycr/Lightning-Browser/issues/445 "Hello, according to http://html5test.com/ lightning 4.3.3 does not support mpeg-4 asp and also adapative bitrate for videos seems to be unsupported. Maybe that's why I had a few problems with videos recently. E.g. twitter inline videos do nothing and a mp4 I had was just offered to download. YouTube seems be fine although.
Do you think the video support can be improved?"

Is here smb with the same problem or ideas for improvements?

**Comment by nutellarlz** [comment]
I've run the http://html5test.com/ site on JumpGo and (unsurprisingly) found the same result of a lack-of-support for mpeg-4 asp and think this may be a problem in the webview component in Android as it is also not supported by many other browsers using the Android System WebView component also lack the same compatibility. However I will try to see if I can integrate a codec that supports mpeg-4 asp as I also have found some issues with video playback. Thanks for pointing this out.

**Comment by herndlm** [comment]
Ah I see, that makes sense. May be system dependant. I noticed that it works in the default browser (gello on cm13 for titan) and e.g. in Firefox/icecat. I'm pretty sure that it worked a few months ago, maybe cm was tinkering smth. Without google on my device its also not possible to simply update the webview components I guess.
EDIT: BTW I have the same problems with https://f-droid.org/app/am.zoom.mbrowser and this was the simplest webview based browser I could find. Its smaller than 300kb and I'm pretty sure it doesn't ship a rendering engine on its own ;)
Thanks for looking into it!
